"""Error code constants for API error responses."""

INVALID_API_KEY = "INVALID_API_KEY"
KEY_NOT_FOUND = "KEY_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
INVALID_AUTH_TOKEN = "INVALID_AUTH_TOKEN"
